/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package filtering;

import CRUD.CRUD;
import StringManipulation.RemoveHTMLTags;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.awt.List;
import java.sql.DriverManager;
import java.util.ArrayList;
import java.util.Collections;

/**
 *
 * @author mariscalyu_SD2082
 */
public class BigData extends javax.swing.JFrame {

    /**
     * Creates new form BigData
     */
    public BigData() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        canvas1 = new java.awt.Canvas();
        jScrollPane1 = new javax.swing.JScrollPane();
        originalWords = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        filteredWords = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        countedWords = new javax.swing.JTextArea();
        remove = new javax.swing.JButton();
        count = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        originalWords.setColumns(20);
        originalWords.setRows(5);
        jScrollPane1.setViewportView(originalWords);

        filteredWords.setColumns(20);
        filteredWords.setRows(5);
        jScrollPane2.setViewportView(filteredWords);

        countedWords.setColumns(20);
        countedWords.setRows(5);
        jScrollPane3.setViewportView(countedWords);

        remove.setText("REMOVE HTML TAGS");
        remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeMouseClicked(evt);
            }
        });
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        count.setText("COUNT WORDS");
        count.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                countMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(count)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(remove)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(count)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(38, Short.MAX_VALUE)
                        .addComponent(remove)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        // TODO add your handling code h\ere:
    }//GEN-LAST:event_removeActionPerformed

    private void removeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeMouseClicked
        //ur handling code here:\
        String str = originalWords.getText();
        RemoveHTMLTags remove = new RemoveHTMLTags();
        str = remove.removeHTML(str);
        filteredWords.setText(str);

    }//GEN-LAST:event_removeMouseClicked

    private void countMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countMouseClicked
        // TODO add your handling code here:
        CRUD c = new CRUD();

       String sentence = filteredWords.getText();
       String[] words = sentence.split("\\W");
//        CONTAINER OF EVERY WORDS no repeat
       ArrayList<String> uniqueWords = new ArrayList();
       ArrayList<String> finalOutput = new ArrayList();
       String output = "";
       for (String word : words) {
           if (!uniqueWords.contains(word) && !word.isEmpty()) {
               uniqueWords.add(word);
           }
       }
       for (String text : uniqueWords) {
           int counter = 0;
           for (String original : words) {
               if (original.equals(text)) {
                   counter++;
               }
           }
           finalOutput.add(text + " = " + counter);
           try
            {
              // create a mysql database connection
              String myDriver ="com.mysql.jdbc.Driver";
              String myUrl = "jdbc:mysql://localhost/bigdata";
              Class.forName(myDriver);
              Connection conn = (Connection) DriverManager.getConnection(myUrl, "root", "");
              
              // the mysql insert statement
              String query = " insert into countword(word,count,school)"
                + " values (?,?,?)";

              // create the mysql insert preparedstatement
              PreparedStatement preparedStmt = (PreparedStatement) conn.prepareStatement(query);
              preparedStmt.setString (1,text);
              preparedStmt.setInt(2,counter);
              preparedStmt.setString(3,"USC");
              // execute the preparedstatement
              preparedStmt.execute();

              conn.close();
            }
            catch (Exception e)
            {
              System.err.println(e);
              
            }            
       }
       for (String res : finalOutput) {
           output += res + "\n";
       }
       countedWords.setText(output);
                      
    }//GEN-LAST:event_countMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BigData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BigData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BigData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BigData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BigData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Canvas canvas1;
    private javax.swing.JButton count;
    private javax.swing.JTextArea countedWords;
    private javax.swing.JTextArea filteredWords;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea originalWords;
    private javax.swing.JButton remove;
    // End of variables declaration//GEN-END:variables
}
